Fix android SDK5

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -14,10 +14,16 @@ jobs:
 
     steps:
 
+      # ==========================
+      # Checkout Source
+      # ==========================
       - name: Checkout
         uses: actions/checkout@v4
 
 
+      # ==========================
+      # Install Linux Dependencies
+      # ==========================
       - name: Install dependencies
         run: |
           sudo apt-get update
@@ -38,45 +44,110 @@ jobs:
             libffi-dev \
             libssl-dev
 
-          pip install --upgrade pip
-          pip install buildozer==1.5.0 Cython==0.29.36
+          python3 -m pip install --upgrade pip
+
+          pip install \
+            buildozer==1.5.0 \
+            Cython==0.29.36
 
 
+      # ==========================
+      # Setup Android SDK
+      # ==========================
       - name: Setup Android SDK
+        shell: bash
         run: |
 
           echo "ANDROID_HOME=$ANDROID_HOME"
 
-          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
+          echo "Searching sdkmanager..."
+
+          SDKMANAGER=$(find $ANDROID_HOME -name sdkmanager | head -n 1)
+
+          if [ -z "$SDKMANAGER" ]; then
+              echo "sdkmanager not found"
+              exit 1
+          fi
+
+
+          echo "Found:"
+          echo $SDKMANAGER
+
+
+          SDK_PATH=$(dirname $SDKMANAGER)
+
+          echo $SDK_PATH >> $GITHUB_PATH
+
           echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
 
-          yes | sdkmanager --licenses || true
 
-          sdkmanager \
+          echo "Accept licenses"
+
+          yes | $SDKMANAGER --licenses || true
+
+
+          echo "Install Android packages"
+
+
+          $SDKMANAGER \
             "platform-tools" \
             "platforms;android-35" \
             "build-tools;35.0.0"
 
 
-      - name: Configure Buildozer SDK
+
+      # ==========================
+      # Verify Android Tools
+      # ==========================
+      - name: Check Android Tools
+        run: |
+
+          which sdkmanager
+
+          sdkmanager --version
+
+          echo "Build Tools:"
+          ls $ANDROID_HOME/build-tools
+
+          echo "AIDL:"
+          find $ANDROID_HOME -name aidl
+
+
+
+      # ==========================
+      # Clear Buildozer Cache
+      # ==========================
+      - name: Clean Buildozer
         run: |
 
           rm -rf ~/.buildozer
 
           mkdir -p ~/.buildozer/android/platform
 
+
           ln -s \
           $ANDROID_HOME \
           ~/.buildozer/android/platform/android-sdk
 
 
+
+      # ==========================
+      # Build APK
+      # ==========================
       - name: Build APK
         run: |
+
           buildozer -v android debug
 
 
+
+      # ==========================
+      # Upload APK
+      # ==========================
       - name: Upload APK
         uses: actions/upload-artifact@v4
         with:
+
           name: CountStock-APK
+
           path: bin/*.apk
